release:
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"

builds:
- env:
    - CGO_ENABLED=0
  goos:
    - freebsd
    - windows
    - darwin
    - linux
    - dragonfly
    - netbsd
    - openbsd
  goarch:
    - amd64
    - arm
    - arm64
    - 386
  goarm:
    - 6
    - 7
  ldflags:
    - -s -w -X github.com/42wim/vshare/version.GitHash={{.ShortCommit}}

archives:
  -
    id: vshare 
    builds:
    - vshare 
    name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: binary
    files:
      - none*

checksum:
  name_template: 'checksums.txt'
